# Example 1 (ver2)

```{r initial setup}
library(matlib)
library(knitr)
library(rmarkdown)
library(quarto)
```

## Find all solution of systems of linear equations of the form **Ax=b**, where:
```{r equationsmatrix}
A <- matrix(
        c(-2, 1, 0,  2,
           3,-2, 0, -5,
          -2, 3, 2, 12,
           2,-2,-1, -7), 4, 4, byrow=TRUE)

colnames(A) <- paste0('x', 1:4)
```

```{r righthandside}
b <- c(-3, 5, -3, 3)
```

### Show equations (in Latex):
```{r eqn}
showEqn(A, b, fractions = TRUE, latex = TRUE)
```

$$
\begin{array}{lllllllll}
-2 \cdot x_1 &+& 1 \cdot x_2 &+& 0 \cdot x_3  &+& 2 \cdot x_4  &=&  -3 \\ 
 3 \cdot x_1 &-& 2 \cdot x_2 &+& 0 \cdot x_3  &-& 5 \cdot x_4  &=&   5 \\ 
-2 \cdot x_1 &+& 3 \cdot x_2 &+& 2 \cdot x_3 &+& 12 \cdot x_4  &=&  -3 \\ 
 2 \cdot x_1 &-& 2 \cdot x_2 &-& 1 \cdot x_3  &-& 7 \cdot x_4  &=&   3 \\ 
\end{array}
$$

### Solve equation:
```{r solveab}
Solve(A, b, vars =  paste0(1:ncol(A)))
```

```{r showresult}
# Result:
x1       + x4  =   1 
  x2   + 4*x4  =  -1 
    x3   + x4  =   1 
            0  =   0 
```

```{r solveverbose}
Solve(A, b, verbose = TRUE, fractions = TRUE) ### arrives to solution by going step by step with Gaussian elementary row edits
```

```{r showverbose}
# Showing solution verbose step by step, ie. the row operations, created by `Solve` command above:
Initial matrix:
     x1 x2 x3 x4   
[1,] -2  1  0  2 -3
[2,]  3 -2  0 -5  5
[3,] -2  3  2 12 -3
[4,]  2 -2 -1 -7  3

row: 1 

 exchange rows 1 and 2 
     x1 x2 x3 x4   
[1,]  3 -2  0 -5  5
[2,] -2  1  0  2 -3
[3,] -2  3  2 12 -3
[4,]  2 -2 -1 -7  3

 multiply row 1 by 1/3 
     x1   x2   x3   x4       
[1,]    1 -2/3    0 -5/3  5/3
[2,]   -2    1    0    2   -3
[3,]   -2    3    2   12   -3
[4,]    2   -2   -1   -7    3

 multiply row 1 by 2 and add to row 2 
     x1   x2   x3   x4       
[1,]    1 -2/3    0 -5/3  5/3
[2,]    0 -1/3    0 -4/3  1/3
[3,]   -2    3    2   12   -3
[4,]    2   -2   -1   -7    3

 multiply row 1 by 2 and add to row 3 
     x1   x2   x3   x4       
[1,]    1 -2/3    0 -5/3  5/3
[2,]    0 -1/3    0 -4/3  1/3
[3,]    0  5/3    2 26/3  1/3
[4,]    2   -2   -1   -7    3

 multiply row 1 by 2 and subtract from row 4 
     x1    x2    x3    x4         
[1,]     1  -2/3     0  -5/3   5/3
[2,]     0  -1/3     0  -4/3   1/3
[3,]     0   5/3     2  26/3   1/3
[4,]     0  -2/3    -1 -11/3  -1/3

row: 2 

 exchange rows 2 and 3 
     x1    x2    x3    x4         
[1,]     1  -2/3     0  -5/3   5/3
[2,]     0   5/3     2  26/3   1/3
[3,]     0  -1/3     0  -4/3   1/3
[4,]     0  -2/3    -1 -11/3  -1/3

 multiply row 2 by 3/5 
     x1    x2    x3    x4         
[1,]     1  -2/3     0  -5/3   5/3
[2,]     0     1   6/5  26/5   1/5
[3,]     0  -1/3     0  -4/3   1/3
[4,]     0  -2/3    -1 -11/3  -1/3

 multiply row 2 by 2/3 and add to row 1 
     x1    x2    x3    x4         
[1,]     1     0   4/5   9/5   9/5
[2,]     0     1   6/5  26/5   1/5
[3,]     0  -1/3     0  -4/3   1/3
[4,]     0  -2/3    -1 -11/3  -1/3

 multiply row 2 by 1/3 and add to row 3 
     x1    x2    x3    x4         
[1,]     1     0   4/5   9/5   9/5
[2,]     0     1   6/5  26/5   1/5
[3,]     0     0   2/5   2/5   2/5
[4,]     0  -2/3    -1 -11/3  -1/3

 multiply row 2 by 2/3 and add to row 4 
     x1   x2   x3   x4       
[1,]    1    0  4/5  9/5  9/5
[2,]    0    1  6/5 26/5  1/5
[3,]    0    0  2/5  2/5  2/5
[4,]    0    0 -1/5 -1/5 -1/5

row: 3 

 multiply row 3 by 5/2 
     x1   x2   x3   x4       
[1,]    1    0  4/5  9/5  9/5
[2,]    0    1  6/5 26/5  1/5
[3,]    0    0    1    1    1
[4,]    0    0 -1/5 -1/5 -1/5

 multiply row 3 by 4/5 and subtract from row 1 
     x1   x2   x3   x4       
[1,]    1    0    0    1    1
[2,]    0    1  6/5 26/5  1/5
[3,]    0    0    1    1    1
[4,]    0    0 -1/5 -1/5 -1/5

 multiply row 3 by 6/5 and subtract from row 2 
     x1   x2   x3   x4       
[1,]    1    0    0    1    1
[2,]    0    1    0    4   -1
[3,]    0    0    1    1    1
[4,]    0    0 -1/5 -1/5 -1/5

 multiply row 3 by 1/5 and add to row 4 
     x1 x2 x3 x4   
[1,]  1  0  0  1  1
[2,]  0  1  0  4 -1
[3,]  0  0  1  1  1
[4,]  0  0  0  0  0

row: 4 
x1       + x4  =   1 
  x2   + 4*x4  =  -1 
    x3   + x4  =   1 
```

